USE [master]
GO

/****** Object:  Database [trade]    Script Date: 08.09.2022 20:44:00 ******/
CREATE DATABASE [trade]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'trade', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\trade.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'trade_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\trade_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [trade].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [trade] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [trade] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [trade] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [trade] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [trade] SET ARITHABORT OFF 
GO

ALTER DATABASE [trade] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [trade] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [trade] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [trade] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [trade] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [trade] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [trade] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [trade] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [trade] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [trade] SET  DISABLE_BROKER 
GO

ALTER DATABASE [trade] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [trade] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [trade] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [trade] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [trade] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [trade] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [trade] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [trade] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [trade] SET  MULTI_USER 
GO

ALTER DATABASE [trade] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [trade] SET DB_CHAINING OFF 
GO

ALTER DATABASE [trade] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [trade] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [trade] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [trade] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [trade] SET QUERY_STORE = OFF
GO

ALTER DATABASE [trade] SET  READ_WRITE 
GO

